steps:
  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ["-"]
    args:
      - functions
      - deploy
      - googlecloudbot_http
      - --runtime=python37
      - --trigger-http
      - --region=us-west1
      - --memory=128MB
    id: "deploying-a-serverless-function"
    dir: "osm-city-boundaries"
