name: deploy_osm_city_boundaries

on:
  push:
    paths:
      - "osm-city-boundaries/**"

jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      # checkout source code
      - uses: actions/checkout@v3

      # authenticate to GCP
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      # Deploy cloud function
      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v0"
        with:
          name: "load_city_boundaries"
          runtime: python310
          source_dir: "./osm-city-boundaries/"
          entry_point: "load_city_boundaries"
          max_instances: 1
          event_trigger_type: "google.storage.object.finalize"
          event_trigger_resource: "projects/tokyo-house-366821/buckets/bucket-osm-9755a02f7829dc9a"
