name: deploy_google_maps_directions_api

on:
  push:
    paths:
      - "google-maps-directions-api/**"

jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      # checkout source code
      - uses: actions/checkout@v3

      # authenticate to GCP
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      # Deploy cloud function
      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v0"
        with:
          name: "hello_pubsub"
          runtime: python310
          env_vars: GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}
          source_dir: "./google-maps-directions-api/"
          entry_point: "hello_pubsub"
          max_instances: 1
          event_trigger_type: "providers/cloud.pubsub/eventTypes/topic.publish"
          event_trigger_resource: "projects/tokyo-house-366821/topics/pubsub-topic-google-directions-trigger"
